### ISSUE TITLE
Breaking changes for 2.0

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#251]
This issue will encapsulate breaking changes that we're considering for a future `2.0` release.  Things like removing deprecated functionality,  removing incorrect classes / methods, changing parts of the design, etc.   

These items can go into the [2.0 branch](https://github.com/eclipse/microprofile-open-api/tree/2.0).

To add an item to this list please add a comment.  

Current list of `2.0` proposals:

- [ ] update extensible and non-extensible
    Links: [models](https://github.com/eclipse/microprofile-open-api/issues/251#issuecomment-409778777) 
- [ ] Remove methods that were renamed (and deprecated) in 1.1 
    Links: [256](https://github.com/eclipse/microprofile-open-api/pull/256)  [261](https://github.com/eclipse/microprofile-open-api/pull/261) [268](https://github.com/eclipse/microprofile-open-api/pull/268) [280](https://github.com/eclipse/microprofile-open-api/pull/280)
- [ ] Delegate document / property location to MP Config 
    Links: [Arch Board 46](https://github.com/eclipse/microprofile/issues/46)
- [ ] (#240) All getters returning a list or a map MUST return copy of this list/map containing the same items. This list/map CAN be immutable
- [ ] (#284) The setters having a list or a map as parameter MUST not use the list/map instance directly (it can be for example an immutable list/map)
- [ ] (#345) Removal of the `Scopes` mode
- [ ] (#348) Remove ServerVariables
- [ ] (#352) Removed parameter target in Parameters annotation
- [ ] (#384) Add SchemaProperty Annotation

**Comment by arthurdm** [comment]
From #248 (thx to @jmini and @EricWittmann):  
- replacing the non-extensible model interfaces with a map version in the appropriate encapsulating model.
- update extensible model interfaces to not extend from `Map`, and instead just contain a map as an internal field - exposing the non-mutable collection, and appropriate add and remove methods.

**Comment by jmini** [comment]
Will you create a new branch to start to work on this version? This way PRs can be opened to start to work on this.

**Comment by arthurdm** [comment]
Yup, good point.  Created: https://github.com/eclipse/microprofile-open-api/tree/2.0

**Comment by jmini** [comment]
Remove methods that were renamed (and deprecated) in 1.1: #256

**Comment by arthurdm** [comment]
thx - added to list

**Comment by jmini** [comment]
For this point:
> Remove methods that were renamed (and deprecated) in 1.1

Add: #261

**Comment by arthurdm** [comment]
added

**Comment by arthurdm** [comment]
We should also look into the issues from the MP Arch board that relate to MP OpenAPI as possible `2.0` candidates.

**Comment by jmini** [comment]
For this point:
> Remove methods that were renamed (and deprecated) in 1.1

Add #268

**Comment by arthurdm** [comment]
added

**Comment by arthurdm** [comment]
added

**Comment by jmini** [comment]
For this point:
> Remove methods that were renamed (and deprecated) in 1.1

Add #281

**Comment by jmini** [comment]
I think the work made with for list/maps in the OpenAPI model interfaces needs to be mentioned as (breaking?) change for`2.0`: 

* (#240) All getters returning a list or a map MUST return copy of this list/map containing the same items. This list/map CAN be immutable
* (#284) The setters having a list or a map as parameter MUST not use the list/map instance directly (it can be for example an immutable list/map)

With `2.0` some tests in the TCK ensure that it works like this (with `1.1` it can work like this but it is up to the vendors)

**Comment by arthurdm** [comment]
updated

**Comment by arthurdm** [comment]
I would like to throw in the idea of removing `OASFilter` and `OASModeReader` from the spec in the `2.0` version.   The benefits would be an easier-to-understand spec, and would allow full compatibility with an `offline` (via Maven or other) generation of the OAS3 doc.  

I believe that modern usage of OAS3 is either via top-down / design-first, where you have the doc generated by a design team, or bottom-up / code-first, where the developer iteratively works on the JAX-RS app, generating it every time. 

 In both cases there is a point in time where development is frozen and no more changes to the API should be allowed.   Therefore, why would we want to use a dynamic filter or model builder?     The only dynamic setting I can reasonably accept are changes to the `server` element, which can already be achieved by configuring the `mp.openapi.servers.*` related keys via MP Config.

Thoughts?

**Comment by jmini** [comment]
> Thoughts?

Lets continue the discussion here: https://github.com/eclipse/microprofile-open-api/issues/300

**Comment by jmini** [comment]
Input from @Emily-Jiang on the mailing list:

> If backward incompatible changes are introduced in the current spec, which making the spec major version increase, e.g. updating Open API 1.1 -> Open API 2.0. The apps using Open API 1.1 no longer works on Open API 2.0, if Open API 2.0 is to be included in the umbrella spec, the umbrella spec major version needs to change, as per documented [here](https://wiki.eclipse.org/MicroProfile/SpecVersioning).

This means that in order to have our `2.0` version in the umbrella spec, an MicroProfile 3.0 will be requested.

My opinion is that for the moment the changes introduced in our `2.0` version are to small to do this move.

**Comment by arthurdm** [comment]
I agree @jmini - let's keep an eye out this year for other specs potentially also in this situation (i.e. about to force an umbrella `3.0` version) and target our `2.0` to go along with them.    There's nothing very urgent in `2.0` so far, and we can do a few of the `MR` builds if needed.

**Comment by arthurdm** [comment]
The master branch now has the 2.0 changes!    I think all there is left to do now is to start the 2.0 release notes and include the stuff in this workitem.

**Comment by MikeEdgar** [comment]
@arthurdm - a few more for the list:

[#352] Removed parameter target in Parameters annotation
[#384] Add SchemaProperty Annotation

**Comment by arthurdm** [comment]
thanks @MikeEdgar - added.
